<?php
/**
 * ApexSMM - Enterprise SMM Panel Platform
 * Web Installer Wizard
 * Configures DB connection, runs schema & seeds, creates admin account, creates install.lock
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

$lockFile = __DIR__ . '/install.lock';
if (file_exists($lockFile)) {
    die("<!DOCTYPE html><html><head><title>ApexSMM Installed</title><link rel='stylesheet' href='/assets/css/style.css'><style>body{background:#f8fafc;color:#0f172a;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;font-family:-apple-system,BlinkMacSystemFont,sans-serif;}div{background:#ffffff;padding:36px;border-radius:16px;border:1px solid #e2e8f0;box-shadow:0 10px 25px rgba(0,0,0,0.05);text-align:center;max-width:480px;}h2{margin-bottom:12px;font-size:20px;font-weight:700;color:#0f172a;}p{color:#64748b;font-size:14px;margin-bottom:20px;}code{background:#f1f5f9;padding:2px 6px;border-radius:4px;color:#7c3aed;font-size:13px;}</style></head><body><div><h2>ApexSMM is already installed</h2><p>For security, the installer is locked. To re-run, remove <code>install/install.lock</code>.</p><p><a href='/' class='btn btn-primary'>Go to Homepage &rarr;</a></p></div></body></html>");
}

$step = (int)($_GET['step'] ?? 1);
$errors = [];
$successMsg = '';

// Step 1: Requirements Check
$requirements = [
    'PHP Version >= 8.2' => version_compare(PHP_VERSION, '8.2.0', '>='),
    'PDO Extension'      => extension_loaded('pdo'),
    'PDO MySQL Driver'   => extension_loaded('pdo_mysql'),
    'cURL Extension'     => extension_loaded('curl'),
    'mbstring Extension' => extension_loaded('mbstring'),
    'OpenSSL Extension'  => extension_loaded('openssl'),
    'JSON Extension'     => extension_loaded('json'),
    'Config writable'    => is_writable(__DIR__ . '/../config') || is_writable(__DIR__ . '/../config/database.php'),
];

$allPassed = !in_array(false, $requirements, true);

// Step 2: Database and Admin Setup Form Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost = trim($_POST['db_host'] ?? '127.0.0.1');
    $dbPort = (int)($_POST['db_port'] ?? 3306);
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? 'root');
    $dbPass = $_POST['db_pass'] ?? '';

    $adminUser = trim($_POST['admin_username'] ?? 'admin');
    $adminEmail = trim($_POST['admin_email'] ?? 'admin@apexsmm.com');
    $adminPass = $_POST['admin_password'] ?? '';
    $siteName = trim($_POST['site_name'] ?? 'ApexSMM Enterprise');

    if (empty($dbName)) $errors[] = "Database name is required.";
    if (empty($adminUser) || strlen($adminUser) < 3) $errors[] = "Admin username must be at least 3 characters.";
    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = "Valid admin email is required.";
    if (strlen($adminPass) < 6) $errors[] = "Admin password must be at least 6 characters.";

    if (empty($errors)) {
        try {
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            // Execute schema
            $schemaFile = dirname(__DIR__) . '/database/schema.sql';
            if (file_exists($schemaFile)) {
                $sql = file_get_contents($schemaFile);
                $pdo->exec($sql);
            }

            // Create admin user
            $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);
            $adminApiKey = 'smm_admin_' . bin2hex(random_bytes(24));

            $stmt = $pdo->prepare("INSERT INTO users (username, email, password, role, balance, spent, status, api_key) VALUES (:u, :e, :p, 'admin', 500.00, 0.00, 'active', :k) ON DUPLICATE KEY UPDATE password = :p2");
            $stmt->execute([
                ':u'  => $adminUser,
                ':e'  => $adminEmail,
                ':p'  => $hashedPass,
                ':k'  => $adminApiKey,
                ':p2' => $hashedPass,
            ]);

            // Save Database Configuration
            $dbConfigFile = dirname(__DIR__) . '/config/database.php';
            $dbConfigContent = "<?php\n/**\n * Generated by ApexSMM Installer\n */\nreturn [\n    'driver'    => 'mysql',\n    'host'      => '{$dbHost}',\n    'port'      => {$dbPort},\n    'database'  => '{$dbName}',\n    'username'  => '{$dbUser}',\n    'password'  => '{$dbPass}',\n    'charset'   => 'utf8mb4',\n    'collation' => 'utf8mb4_unicode_ci',\n    'options'   => [\n        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n        PDO::ATTR_EMULATE_PREPARES   => false,\n    ],\n];\n";
            @file_put_contents($dbConfigFile, $dbConfigContent);

            // Write Installation Lock
            file_put_contents($lockFile, date('Y-m-d H:i:s') . " - Installed successfully.");

            $step = 3; // Finished
        } catch (PDOException $e) {
            $errors[] = "Database Connection Failed: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ApexSMM Installation Wizard</title>
    <link rel="stylesheet" href="/assets/css/style.css">
    <style>
        body {
            background-color: var(--bg-body, #f8fafc);
            color: var(--text-primary, #0f172a);
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            padding: 24px;
        }
        .installer-wrapper {
            width: 100%;
            max-width: 620px;
        }
        .installer-card {
            background-color: #ffffff;
            border: 1px solid var(--border, #e2e8f0);
            border-radius: 16px;
            box-shadow: 0 10px 25px -3px rgba(0, 0, 0, 0.08);
            overflow: hidden;
        }
        .installer-header {
            padding: 28px 32px;
            border-bottom: 1px solid var(--border, #e2e8f0);
            background: linear-gradient(135deg, #f5f3ff 0%, #ffffff 100%);
            display: flex;
            align-items: center;
            gap: 16px;
        }
        .installer-body { padding: 32px; }
        .req-list { list-style: none; margin-bottom: 24px; }
        .req-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 16px;
            background: #ffffff;
            border: 1px solid var(--border, #e2e8f0);
            border-radius: 8px;
            margin-bottom: 8px;
            font-size: 14px;
        }
        .badge-pass { background: #ecfdf5; color: #047857; border: 1px solid #a7f3d0; }
        .badge-fail { background: #fef2f2; color: #b91c1c; border: 1px solid #fecaca; }
        .section-heading {
            font-size: 15px;
            font-weight: 700;
            color: var(--text-primary, #0f172a);
            margin: 20px 0 12px;
            padding-bottom: 6px;
            border-bottom: 1px solid var(--border, #e2e8f0);
        }
    </style>
</head>
<body class="theme-light">
<div class="installer-wrapper">
    <div class="installer-card">
        <div class="installer-header">
            <div class="logo-icon">
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>
            </div>
            <div>
                <h1 style="font-size: 20px; font-weight: 800; color: #0f172a;">Apex<span style="color: #7c3aed;">SMM</span> Enterprise Installer</h1>
                <p style="color: #64748b; font-size: 13px; margin-top: 2px;">Step <?= $step ?> of 3: <?= $step === 1 ? 'Server Requirements Verification' : ($step === 2 ? 'Database & Administrator Setup' : 'Installation Finished') ?></p>
            </div>
        </div>
        <div class="installer-body">
            <?php if (!empty($errors)): ?>
                <div class="alert alert-error">
                    <span class="alert-icon"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg></span>
                    <div class="alert-content">
                        <?php foreach ($errors as $e): ?>
                            <div>&bull; <?= htmlspecialchars($e) ?></div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($step === 1): ?>
                <ul class="req-list">
                    <?php foreach ($requirements as $name => $passed): ?>
                        <li class="req-item">
                            <span style="font-weight: 500;"><?= htmlspecialchars($name) ?></span>
                            <span class="badge <?= $passed ? 'badge-pass' : 'badge-fail' ?>">
                                <?= $passed ? 'AVAILABLE' : 'MISSING' ?>
                            </span>
                        </li>
                    <?php endforeach; ?>
                </ul>

                <?php if ($allPassed): ?>
                    <a href="?step=2" class="btn btn-primary btn-block btn-lg">Continue to Database Setup &rarr;</a>
                <?php else: ?>
                    <p style="color: var(--danger, #ef4444); font-size: 14px; margin-bottom: 16px;">Some server requirements are missing. Please verify PHP extensions before proceeding.</p>
                    <a href="?step=1" class="btn btn-secondary btn-block">Re-check Requirements</a>
                <?php endif; ?>

            <?php elseif ($step === 2): ?>
                <form method="POST" action="?step=2">
                    <div class="section-heading">Database Connection (MySQL 8+ / MariaDB)</div>
                    <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 12px;">
                        <div class="form-group">
                            <label>Host</label>
                            <input type="text" name="db_host" class="form-control" value="127.0.0.1" required>
                        </div>
                        <div class="form-group">
                            <label>Port</label>
                            <input type="number" name="db_port" class="form-control" value="3306" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Database Name</label>
                        <input type="text" name="db_name" class="form-control" placeholder="smm_panel" required>
                    </div>
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" name="db_user" class="form-control" value="root" required>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" name="db_pass" class="form-control" placeholder="Optional">
                        </div>
                    </div>

                    <div class="section-heading">Master Administrator Account</div>
                    <div class="form-group">
                        <label>Admin Username</label>
                        <input type="text" name="admin_username" class="form-control" value="admin" required>
                    </div>
                    <div class="form-group">
                        <label>Admin Email</label>
                        <input type="email" name="admin_email" class="form-control" value="admin@apexsmm.com" required>
                    </div>
                    <div class="form-group">
                        <label>Admin Password</label>
                        <input type="password" name="admin_password" class="form-control" required placeholder="Minimum 6 characters">
                    </div>

                    <button type="submit" class="btn btn-primary btn-block btn-lg" style="margin-top: 12px;">Install ApexSMM & Migrate DB</button>
                </form>

            <?php elseif ($step === 3): ?>
                <div style="text-align: center; padding: 20px 0;">
                    <div style="width: 60px; height: 60px; border-radius: 50%; background: #ecfdf5; color: #059669; border: 1px solid #a7f3d0; display: flex; align-items: center; justify-content: center; font-size: 28px; margin: 0 auto 16px;">&#10003;</div>
                    <h2 style="font-size: 20px; font-weight: 700; margin-bottom: 8px;">Installation Completed!</h2>
                    <p style="color: #64748b; font-size: 14px; margin-bottom: 24px;">Your database tables have been migrated, demo services seeded, and the installation lock has been created.</p>
                    <a href="/login.php" class="btn btn-primary btn-block btn-lg">Proceed to Sign In &rarr;</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</body>
</html>
