<?php
/**
 * ApexSMM - Enterprise SMM Panel Platform
 * Web Installer Wizard
 * Configures DB connection, runs schema & seeds, creates admin account, creates install.lock
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

$lockFile = __DIR__ . '/install.lock';
if (file_exists($lockFile)) {
    die("<!DOCTYPE html><html><head><title>ApexSMM Installed</title><style>body{font-family:system-ui;background:#090d16;color:#e2e8f0;display:flex;align-items:center;justify-content:center;height:100vh;margin:0;}div{background:#111827;padding:30px;border-radius:12px;border:1px solid #1f2937;text-align:center;max-width:480px;}</style></head><body><div><h2>ApexSMM is already installed</h2><p>For security, the installer is locked. To re-run, delete <code>install/install.lock</code>.</p><p><a href='/' style='color:#3b82f6;'>Go to Homepage &rarr;</a></p></div></body></html>");
}

$step = (int)($_GET['step'] ?? 1);
$errors = [];
$successMsg = '';

// Step 1: Requirements Check
$requirements = [
    'PHP Version >= 8.2' => version_compare(PHP_VERSION, '8.2.0', '>='),
    'PDO Extension'      => extension_loaded('pdo'),
    'PDO MySQL Driver'   => extension_loaded('pdo_mysql'),
    'cURL Extension'     => extension_loaded('curl'),
    'mbstring Extension' => extension_loaded('mbstring'),
    'OpenSSL Extension'  => extension_loaded('openssl'),
    'JSON Extension'     => extension_loaded('json'),
    'Config writable'    => is_writable(__DIR__ . '/../config') || is_writable(__DIR__ . '/../config/database.php'),
];

$allPassed = !in_array(false, $requirements, true);

// Step 2: Database and Admin Setup Form Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost = trim($_POST['db_host'] ?? '127.0.0.1');
    $dbPort = (int)($_POST['db_port'] ?? 3306);
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? 'root');
    $dbPass = $_POST['db_pass'] ?? '';

    $adminUser = trim($_POST['admin_username'] ?? 'admin');
    $adminEmail = trim($_POST['admin_email'] ?? 'admin@apexsmm.com');
    $adminPass = $_POST['admin_password'] ?? '';
    $siteName = trim($_POST['site_name'] ?? 'ApexSMM Enterprise');

    if (empty($dbName)) $errors[] = "Database name is required.";
    if (empty($adminUser) || strlen($adminUser) < 3) $errors[] = "Admin username must be at least 3 characters.";
    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = "Valid admin email is required.";
    if (strlen($adminPass) < 6) $errors[] = "Admin password must be at least 6 characters.";

    if (empty($errors)) {
        try {
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            // Execute schema
            $schemaFile = dirname(__DIR__) . '/database/schema.sql';
            if (file_exists($schemaFile)) {
                $sqlContent = file_get_contents($schemaFile);
                $pdo->exec($sqlContent);
            }

            // Update or Insert custom Admin
            $hashedPass = password_hash($adminPass, PASSWORD_BCRYPT, ['cost' => 12]);
            $apiKey = 'smm_' . bin2hex(random_bytes(28));

            $stmt = $pdo->prepare("SELECT id FROM users WHERE id = 1");
            $stmt->execute();
            if ($stmt->fetch()) {
                $upd = $pdo->prepare("UPDATE users SET username = :u, email = :e, password = :p, api_key = :k WHERE id = 1");
                $upd->execute([':u' => $adminUser, ':e' => $adminEmail, ':p' => $hashedPass, ':k' => $apiKey]);
            } else {
                $ins = $pdo->prepare("INSERT INTO users (id, username, email, password, role, balance, status, api_key) VALUES (1, :u, :e, :p, 'admin', 500.00, 'active', :k)");
                $ins->execute([':u' => $adminUser, ':e' => $adminEmail, ':p' => $hashedPass, ':k' => $apiKey]);
            }

            // Save Database Configuration
            $dbConfigFile = dirname(__DIR__) . '/config/database.php';
            $dbConfigContent = "<?php\n/**\n * Generated by ApexSMM Installer\n */\nreturn [\n    'driver'    => 'mysql',\n    'host'      => '{$dbHost}',\n    'port'      => {$dbPort},\n    'database'  => '{$dbName}',\n    'username'  => '{$dbUser}',\n    'password'  => '{$dbPass}',\n    'charset'   => 'utf8mb4',\n    'collation' => 'utf8mb4_unicode_ci',\n    'options'   => [\n        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n        PDO::ATTR_EMULATE_PREPARES   => false,\n    ],\n];\n";
            @file_put_contents($dbConfigFile, $dbConfigContent);

            // Write Installation Lock
            file_put_contents($lockFile, date('Y-m-d H:i:s') . " - Installed successfully.");

            $step = 3; // Finished
        } catch (PDOException $e) {
            $errors[] = "Database Connection Failed: " . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ApexSMM Installation Wizard</title>
    <style>
        :root {
            --bg-body: #090d16;
            --bg-card: #111827;
            --border: #1f2937;
            --text-primary: #f8fafc;
            --text-muted: #94a3b8;
            --accent: #3b82f6;
            --accent-hover: #2563eb;
            --success: #10b981;
            --danger: #ef4444;
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background-color: var(--bg-body);
            color: var(--text-primary);
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            padding: 24px;
        }
        .installer-card {
            background-color: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            width: 100%;
            max-width: 600px;
            box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5);
            overflow: hidden;
        }
        .header {
            padding: 28px 32px;
            border-bottom: 1px solid var(--border);
            background: linear-gradient(180deg, #1e293b 0%, #111827 100%);
        }
        .header h1 { font-size: 22px; font-weight: 700; }
        .header p { color: var(--text-muted); font-size: 14px; margin-top: 4px; }
        .body { padding: 32px; }
        .req-list { list-style: none; margin-bottom: 24px; }
        .req-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 12px 16px;
            background: rgba(255,255,255,0.02);
            border: 1px solid var(--border);
            border-radius: 8px;
            margin-bottom: 8px;
            font-size: 14px;
        }
        .badge {
            font-size: 12px;
            font-weight: 600;
            padding: 4px 10px;
            border-radius: 9999px;
        }
        .badge-pass { background: rgba(16, 185, 129, 0.2); color: var(--success); }
        .badge-fail { background: rgba(239, 68, 68, 0.2); color: var(--danger); }
        .btn {
            display: inline-block;
            background: var(--accent);
            color: #fff;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 600;
            font-size: 15px;
            text-decoration: none;
            border: none;
            cursor: pointer;
            width: 100%;
            text-align: center;
        }
        .btn:hover { background: var(--accent-hover); }
        .form-group { margin-bottom: 16px; }
        .form-group label { display: block; font-size: 13px; font-weight: 500; color: var(--text-muted); margin-bottom: 6px; }
        .form-control {
            width: 100%;
            padding: 10px 14px;
            background: #0f172a;
            border: 1px solid var(--border);
            border-radius: 8px;
            color: #fff;
            font-size: 14px;
        }
        .form-control:focus { outline: none; border-color: var(--accent); }
        .alert-error {
            background: rgba(239, 68, 68, 0.15);
            border: 1px solid rgba(239, 68, 68, 0.3);
            color: #fca5a5;
            padding: 14px;
            border-radius: 8px;
            margin-bottom: 20px;
            font-size: 13px;
        }
        .section-title {
            font-size: 15px;
            font-weight: 600;
            margin: 20px 0 12px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 8px;
        }
    </style>
</head>
<body>
<div class="installer-card">
    <div class="header">
        <h1>ApexSMM Enterprise Installer</h1>
        <p>Step <?= $step ?> of 3: <?= $step === 1 ? 'Server Requirements' : ($step === 2 ? 'Database & Admin Setup' : 'Installation Complete') ?></p>
    </div>
    <div class="body">
        <?php if (!empty($errors)): ?>
            <div class="alert-error">
                <?php foreach ($errors as $e): ?>
                    <div>&bull; <?= htmlspecialchars($e) ?></div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if ($step === 1): ?>
            <ul class="req-list">
                <?php foreach ($requirements as $name => $passed): ?>
                    <li class="req-item">
                        <span><?= htmlspecialchars($name) ?></span>
                        <span class="badge <?= $passed ? 'badge-pass' : 'badge-fail' ?>">
                            <?= $passed ? 'PASSED' : 'FAILED' ?>
                        </span>
                    </li>
                <?php endforeach; ?>
            </ul>

            <?php if ($allPassed): ?>
                <a href="?step=2" class="btn">Continue to Database Setup &rarr;</a>
            <?php else: ?>
                <p style="color: var(--danger); font-size: 14px; margin-bottom: 16px;">Some server requirements are missing. Please verify PHP extensions before proceeding.</p>
                <a href="?step=1" class="btn" style="background: #374151;">Re-check Requirements</a>
            <?php endif; ?>

        <?php elseif ($step === 2): ?>
            <form method="POST" action="?step=2">
                <div class="section-title">Database Credentials (MySQL / MariaDB)</div>
                <div style="display: grid; grid-template-columns: 2fr 1fr; gap: 12px;">
                    <div class="form-group">
                        <label>Host</label>
                        <input type="text" name="db_host" class="form-control" value="127.0.0.1" required>
                    </div>
                    <div class="form-group">
                        <label>Port</label>
                        <input type="number" name="db_port" class="form-control" value="3306" required>
                    </div>
                </div>
                <div class="form-group">
                    <label>Database Name</label>
                    <input type="text" name="db_name" class="form-control" placeholder="smm_panel" required>
                </div>
                <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                    <div class="form-group">
                        <label>Username</label>
                        <input type="text" name="db_user" class="form-control" value="root" required>
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" name="db_pass" class="form-control" placeholder="Optional">
                    </div>
                </div>

                <div class="section-title">Master Administrator Account</div>
                <div class="form-group">
                    <label>Admin Username</label>
                    <input type="text" name="admin_username" class="form-control" value="admin" required>
                </div>
                <div class="form-group">
                    <label>Admin Email</label>
                    <input type="email" name="admin_email" class="form-control" value="admin@apexsmm.com" required>
                </div>
                <div class="form-group">
                    <label>Admin Password</label>
                    <input type="password" name="admin_password" class="form-control" required placeholder="Minimum 6 characters">
                </div>

                <button type="submit" class="btn" style="margin-top: 12px;">Install ApexSMM & Migrate DB</button>
            </form>

        <?php elseif ($step === 3): ?>
            <div style="text-align: center; padding: 20px 0;">
                <div style="width: 60px; height: 60px; border-radius: 50%; background: rgba(16, 185, 129, 0.2); color: var(--success); display: flex; align-items: center; justify-content: center; font-size: 28px; margin: 0 auto 16px;">&#10003;</div>
                <h2 style="font-size: 20px; margin-bottom: 8px;">Installation Completed!</h2>
                <p style="color: var(--text-muted); font-size: 14px; margin-bottom: 24px;">Your database tables have been migrated, demo services seeded, and the installation lock has been created.</p>
                <a href="/login.php" class="btn">Proceed to Login &rarr;</a>
            </div>
        <?php endif; ?>
    </div>
</div>
</body>
</html>
